/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShippingDeliveryPolicyRouteImport } from './routes/shipping-delivery-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CancellationRefundPolicyRouteImport } from './routes/cancellation-refund-policy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as TTableIdRouteImport } from './routes/t.$tableId'
import { Route as RestaurantDeliveryRouteImport } from './routes/restaurant.delivery'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTablesRouteImport } from './routes/admin.tables'
import { Route as AdminStoreRouteImport } from './routes/admin.store'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryPolicyRoute = ShippingDeliveryPolicyRouteImport.update({
  id: '/shipping-delivery-policy',
  path: '/shipping-delivery-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRefundPolicyRoute =
  CancellationRefundPolicyRouteImport.update({
    id: '/cancellation-refund-policy',
    path: '/cancellation-refund-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => TrackRoute,
} as any)
const TTableIdRoute = TTableIdRouteImport.update({
  id: '/t/$tableId',
  path: '/t/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDeliveryRoute = RestaurantDeliveryRouteImport.update({
  id: '/restaurant/delivery',
  path: '/restaurant/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/shipping-delivery-policy': typeof ShippingDeliveryPolicyRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/delivery': typeof RestaurantDeliveryRoute
  '/t/$tableId': typeof TTableIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/shipping-delivery-policy': typeof ShippingDeliveryPolicyRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/delivery': typeof RestaurantDeliveryRoute
  '/t/$tableId': typeof TTableIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation-refund-policy': typeof CancellationRefundPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/delivery': typeof DeliveryRoute
  '/favorites': typeof FavoritesRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/shipping-delivery-policy': typeof ShippingDeliveryPolicyRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRouteWithChildren
  '/admin/billing': typeof AdminBillingRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/store': typeof AdminStoreRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/restaurant/delivery': typeof RestaurantDeliveryRoute
  '/t/$tableId': typeof TTableIdRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cancellation-refund-policy'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/delivery'
    | '/favorites'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/shipping-delivery-policy'
    | '/signup'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/billing'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/store'
    | '/admin/tables'
    | '/admin/users'
    | '/orders/$orderId'
    | '/restaurant/delivery'
    | '/t/$tableId'
    | '/track/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cancellation-refund-policy'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/delivery'
    | '/favorites'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/shipping-delivery-policy'
    | '/signup'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/billing'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/store'
    | '/admin/tables'
    | '/admin/users'
    | '/orders/$orderId'
    | '/restaurant/delivery'
    | '/t/$tableId'
    | '/track/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cancellation-refund-policy'
    | '/cart'
    | '/checkout'
    | '/contact-us'
    | '/delivery'
    | '/favorites'
    | '/kitchen'
    | '/login'
    | '/menu'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/shipping-delivery-policy'
    | '/signup'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/billing'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/orders'
    | '/admin/store'
    | '/admin/tables'
    | '/admin/users'
    | '/orders/$orderId'
    | '/restaurant/delivery'
    | '/t/$tableId'
    | '/track/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancellationRefundPolicyRoute: typeof CancellationRefundPolicyRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactUsRoute: typeof ContactUsRoute
  DeliveryRoute: typeof DeliveryRoute
  FavoritesRoute: typeof FavoritesRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ShippingDeliveryPolicyRoute: typeof ShippingDeliveryPolicyRoute
  SignupRoute: typeof SignupRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackRoute: typeof TrackRouteWithChildren
  RestaurantDeliveryRoute: typeof RestaurantDeliveryRoute
  TTableIdRoute: typeof TTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-delivery-policy': {
      id: '/shipping-delivery-policy'
      path: '/shipping-delivery-policy'
      fullPath: '/shipping-delivery-policy'
      preLoaderRoute: typeof ShippingDeliveryPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-refund-policy': {
      id: '/cancellation-refund-policy'
      path: '/cancellation-refund-policy'
      fullPath: '/cancellation-refund-policy'
      preLoaderRoute: typeof CancellationRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/t/$tableId': {
      id: '/t/$tableId'
      path: '/t/$tableId'
      fullPath: '/t/$tableId'
      preLoaderRoute: typeof TTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/delivery': {
      id: '/restaurant/delivery'
      path: '/restaurant/delivery'
      fullPath: '/restaurant/delivery'
      preLoaderRoute: typeof RestaurantDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminStoreRoute: typeof AdminStoreRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminStoreRoute: AdminStoreRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface TrackRouteChildren {
  TrackOrderIdRoute: typeof TrackOrderIdRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackOrderIdRoute: TrackOrderIdRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CancellationRefundPolicyRoute: CancellationRefundPolicyRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactUsRoute: ContactUsRoute,
  DeliveryRoute: DeliveryRoute,
  FavoritesRoute: FavoritesRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ShippingDeliveryPolicyRoute: ShippingDeliveryPolicyRoute,
  SignupRoute: SignupRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackRoute: TrackRouteWithChildren,
  RestaurantDeliveryRoute: RestaurantDeliveryRoute,
  TTableIdRoute: TTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
